name: CI
on:
  push:
    branches:
      - 'dev/**'
  release:
    types:
      - published
  pull_request:

jobs:
  build:
    if: ${{ github.event_name == 'push' && !startsWith(github.event.ref, 'refs/tags/') && contains(github.event.head_commit.message, '[build skip]') == false }}
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Preprocess sources
        run: ./gradlew preprocessResources --stacktrace

      - name: Publish Maven with Gradle
        run: ./gradlew build publish -x test --stacktrace

      - name: Upload Maven to GitHub
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: git@github.com:Hendrix-Shen/Maven.git
          BRANCH: master
          FOLDER: publish
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          CLEAR_GLOBS_FILE: '.clear-target-files'

      - name: Create Github release
        if: contains(github.event.head_commit.message, '[publish skip]') == false && contains(github.event.ref, 'refs/heads/exp') == false
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            LICENSE
            fabricWrapper/build/libs/*.jar
            fabricWrapper/tmp/submods/*.jar
          name: "${{ github.ref_name }}.${{ steps.buildnumber.outputs.build_number }}"
          tag_name: "${{ github.ref_name }}.${{ steps.buildnumber.outputs.build_number }}"
          target_commitish: ${{ github.event.ref }}
          generate_release_notes: true

  publish:
    if: ${{ github.event_name == 'release' }}
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the sources
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Generate build number
        id: buildnumber
        run: |
          buildnumber=$(echo ${{ github.ref_name }} | cut -d . -f3)
          echo "::set-output name=buildnumber::$buildnumber"

      - name: Read Properties mod_version
        id: mod_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: gradle.properties
          property: mod_version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Preprocess sources
        run: ./gradlew preprocessResources --stacktrace

      - name: Publish Maven with Gradle
        run: ./gradlew build publish -x test --stacktrace
        env:
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.buildnumber }}

      - name: Upload Maven to GitHub
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: git@github.com:Hendrix-Shen/Maven.git
          BRANCH: master
          FOLDER: publish
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          CLEAR_GLOBS_FILE: '.clear-target-files'

      - name: Upload assets Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.ref }}
          files: |
            LICENSE
            fabricWrapper/build/libs/*.jar
            fabricWrapper/tmp/submods/META-INF/jars/*.jar

      - name: Upload assets to GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.mod_name.outputs.value }} ${{ steps.mod_version.outputs.value }}.${{ steps.buildnumber.outputs.buildnumber }}
          path: |
            LICENSE
            fabricWrapper/build/libs/*.jar
            fabricWrapper/tmp/submods/META-INF/jars/*.jar

      - name: Publish release to CurseForge & Modrinth
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: mv1zH6ln
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          curseforge-id: 576459
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          files-primary: fabricWrapper/build/libs/!(*-@(dev|sources)).jar
          files-secondary: fabricWrapper/tmp/submods/META-INF/jars/!(*-@(dev|sources)).jar

          name: ''
          version: ${{ steps.mod_version.outputs.value }}
          version-type: 'release'

          changelog: ${{ github.event.release.body }}
          loaders:
            fabric
          game-versions: |
            1.14.4
            1.15.2
            1.16.5
            1.17.1
            1.18.2
            1.19
          version-resolver: latest
          java: |
            8
            9
            10
            11
            12
            13
            14
            15
            16
            17
            18

          retry-attempts: 2
          retry-delay: 10000

  pull_request:
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
